#ifndef __PICO1TR_LED_S_CHAR_DATA_H__
#define __PICO1TR_LED_S_CHAR_DATA_H__
///
/// generated by ascii2led
///

extern const uint8_t led_char[][13];
#define LED_CHAR_OFFS 87
#define LED_LAST_ORD 12
#define LED_NUM_ROWS 10
#define LED_NUM_COLS 10


#endif
